// <auto-generated />
using System;
using BiotecsBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BiotecsBack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200811094426_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.ActiveSubstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubstanceName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SubstanceNameEng")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SubstanceNameRu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("ActiveSubstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo1",
                            SubstanceNameEng = "SubstanceNameEng1",
                            SubstanceNameRu = "SubstanceNameRu1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo2 ",
                            SubstanceNameEng = "SubstanceNameEng2 ",
                            SubstanceNameRu = "SubstanceNameRu2 "
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo3 ",
                            SubstanceNameEng = "SubstanceNameEng3 ",
                            SubstanceNameRu = "SubstanceNameRu3 "
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo4 ",
                            SubstanceNameEng = "SubstanceNameEng4 ",
                            SubstanceNameRu = "SubstanceNameRu4 "
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo5 ",
                            SubstanceNameEng = "SubstanceNameEng5 ",
                            SubstanceNameRu = "SubstanceNameRu5 "
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo6 ",
                            SubstanceNameEng = "SubstanceNameEng6 ",
                            SubstanceNameRu = "SubstanceNameRu6 "
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo7 ",
                            SubstanceNameEng = "SubstanceNameEng7 ",
                            SubstanceNameRu = "SubstanceNameRu7 "
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo8 ",
                            SubstanceNameEng = "SubstanceNameEng8 ",
                            SubstanceNameRu = "SubstanceNameRu8 "
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo9 ",
                            SubstanceNameEng = "SubstanceNameEng9 ",
                            SubstanceNameRu = "SubstanceNameRu9 "
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubstanceName = "SubstanceNameGeo10 ",
                            SubstanceNameEng = "SubstanceNameEng10 ",
                            SubstanceNameRu = "SubstanceNameRu10 "
                        });
                });

            modelBuilder.Entity("Data.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArticleText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleTextEng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleTextRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TitleEng")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TitleRu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Data.Models.ArticlePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticlePhotos");
                });

            modelBuilder.Entity("Data.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("GroupNameEng")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("GroupNameRu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "GNameGeo1",
                            GroupNameEng = "GNameEng1",
                            GroupNameRu = "GNameRu1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "GNameGeo2",
                            GroupNameEng = "GNameEng2",
                            GroupNameRu = "GNameRu2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "GNameGeo3",
                            GroupNameEng = "GNameEng3",
                            GroupNameRu = "GNameRu3",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "GNameGeo4",
                            GroupNameEng = "GNameEng4",
                            GroupNameRu = "GNameRu4",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "GNameGeo5",
                            GroupNameEng = "GNameEng5",
                            GroupNameRu = "GNameRu5",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActiveSubstanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ProductNameEng")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ProductNameRu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ActiveSubstanceId");

                    b.HasIndex("GroupId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveSubstanceId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo1",
                            DescriptionEng = "DescriptionEng1",
                            DescriptionRu = "DescriptionRu1",
                            GroupId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo1",
                            ProductNameEng = "ProductNameEng1",
                            ProductNameRu = "ProductNameRu1"
                        },
                        new
                        {
                            Id = 2,
                            ActiveSubstanceId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo2",
                            DescriptionEng = "DescriptionEng2",
                            DescriptionRu = "DescriptionRu2",
                            GroupId = 2,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo2",
                            ProductNameEng = "ProductNameEng2",
                            ProductNameRu = "ProductNameRu2"
                        },
                        new
                        {
                            Id = 3,
                            ActiveSubstanceId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo3",
                            DescriptionEng = "DescriptionEng3",
                            DescriptionRu = "DescriptionRu3",
                            GroupId = 5,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo3",
                            ProductNameEng = "ProductNameEng3",
                            ProductNameRu = "ProductNameRu3"
                        },
                        new
                        {
                            Id = 4,
                            ActiveSubstanceId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo4",
                            DescriptionEng = "DescriptionEng4",
                            DescriptionRu = "DescriptionRu4",
                            GroupId = 5,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo4",
                            ProductNameEng = "ProductNameEng4",
                            ProductNameRu = "ProductNameRu4"
                        },
                        new
                        {
                            Id = 5,
                            ActiveSubstanceId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo5",
                            DescriptionEng = "DescriptionEng5",
                            DescriptionRu = "DescriptionRu5",
                            GroupId = 2,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo5",
                            ProductNameEng = "ProductNameEng5",
                            ProductNameRu = "ProductNameRu5"
                        },
                        new
                        {
                            Id = 6,
                            ActiveSubstanceId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo6",
                            DescriptionEng = "DescriptionEng6",
                            DescriptionRu = "DescriptionRu6",
                            GroupId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo6",
                            ProductNameEng = "ProductNameEng6",
                            ProductNameRu = "ProductNameRu6"
                        },
                        new
                        {
                            Id = 7,
                            ActiveSubstanceId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo7",
                            DescriptionEng = "DescriptionEng7",
                            DescriptionRu = "DescriptionRu7",
                            GroupId = 2,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo7",
                            ProductNameEng = "ProductNameEng7",
                            ProductNameRu = "ProductNameRu7"
                        },
                        new
                        {
                            Id = 8,
                            ActiveSubstanceId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo8",
                            DescriptionEng = "DescriptionEng8",
                            DescriptionRu = "DescriptionRu8",
                            GroupId = 2,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo8",
                            ProductNameEng = "ProductNameEng8",
                            ProductNameRu = "ProductNameRu8"
                        },
                        new
                        {
                            Id = 9,
                            ActiveSubstanceId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo9",
                            DescriptionEng = "DescriptionEng9",
                            DescriptionRu = "DescriptionRu9",
                            GroupId = 3,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo9",
                            ProductNameEng = "ProductNameEng9",
                            ProductNameRu = "ProductNameRu9"
                        },
                        new
                        {
                            Id = 10,
                            ActiveSubstanceId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo10",
                            DescriptionEng = "DescriptionEng10",
                            DescriptionRu = "DescriptionRu10",
                            GroupId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo10",
                            ProductNameEng = "ProductNameEng10",
                            ProductNameRu = "ProductNameRu10"
                        },
                        new
                        {
                            Id = 11,
                            ActiveSubstanceId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo11",
                            DescriptionEng = "DescriptionEng11",
                            DescriptionRu = "DescriptionRu11",
                            GroupId = 2,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo11",
                            ProductNameEng = "ProductNameEng11",
                            ProductNameRu = "ProductNameRu11"
                        },
                        new
                        {
                            Id = 12,
                            ActiveSubstanceId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo12",
                            DescriptionEng = "DescriptionEng12",
                            DescriptionRu = "DescriptionRu12",
                            GroupId = 2,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo12",
                            ProductNameEng = "ProductNameEng12",
                            ProductNameRu = "ProductNameRu12"
                        },
                        new
                        {
                            Id = 13,
                            ActiveSubstanceId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo13",
                            DescriptionEng = "DescriptionEng13",
                            DescriptionRu = "DescriptionRu13",
                            GroupId = 3,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo13",
                            ProductNameEng = "ProductNameEng13",
                            ProductNameRu = "ProductNameRu13"
                        },
                        new
                        {
                            Id = 14,
                            ActiveSubstanceId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo14",
                            DescriptionEng = "DescriptionEng14",
                            DescriptionRu = "DescriptionRu14",
                            GroupId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo14",
                            ProductNameEng = "ProductNameEng14",
                            ProductNameRu = "ProductNameRu14"
                        },
                        new
                        {
                            Id = 15,
                            ActiveSubstanceId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo15",
                            DescriptionEng = "DescriptionEng15",
                            DescriptionRu = "DescriptionRu15",
                            GroupId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo15",
                            ProductNameEng = "ProductNameEng15",
                            ProductNameRu = "ProductNameRu15"
                        },
                        new
                        {
                            Id = 16,
                            ActiveSubstanceId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo16",
                            DescriptionEng = "DescriptionEng16",
                            DescriptionRu = "DescriptionRu16",
                            GroupId = 4,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo16",
                            ProductNameEng = "ProductNameEng16",
                            ProductNameRu = "ProductNameRu16"
                        },
                        new
                        {
                            Id = 17,
                            ActiveSubstanceId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo17",
                            DescriptionEng = "DescriptionEng17",
                            DescriptionRu = "DescriptionRu17",
                            GroupId = 5,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo17",
                            ProductNameEng = "ProductNameEng17",
                            ProductNameRu = "ProductNameRu17"
                        },
                        new
                        {
                            Id = 18,
                            ActiveSubstanceId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo18",
                            DescriptionEng = "DescriptionEng18",
                            DescriptionRu = "DescriptionRu18",
                            GroupId = 5,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo18",
                            ProductNameEng = "ProductNameEng18",
                            ProductNameRu = "ProductNameRu18"
                        },
                        new
                        {
                            Id = 19,
                            ActiveSubstanceId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo19",
                            DescriptionEng = "DescriptionEng19",
                            DescriptionRu = "DescriptionRu19",
                            GroupId = 2,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo19",
                            ProductNameEng = "ProductNameEng19",
                            ProductNameRu = "ProductNameRu19"
                        },
                        new
                        {
                            Id = 20,
                            ActiveSubstanceId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo20",
                            DescriptionEng = "DescriptionEng20",
                            DescriptionRu = "DescriptionRu20",
                            GroupId = 3,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo20",
                            ProductNameEng = "ProductNameEng20",
                            ProductNameRu = "ProductNameRu20"
                        },
                        new
                        {
                            Id = 21,
                            ActiveSubstanceId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo21",
                            DescriptionEng = "DescriptionEng21",
                            DescriptionRu = "DescriptionRu21",
                            GroupId = 4,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo21",
                            ProductNameEng = "ProductNameEng21",
                            ProductNameRu = "ProductNameRu21"
                        },
                        new
                        {
                            Id = 22,
                            ActiveSubstanceId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo22",
                            DescriptionEng = "DescriptionEng22",
                            DescriptionRu = "DescriptionRu22",
                            GroupId = 5,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo22",
                            ProductNameEng = "ProductNameEng22",
                            ProductNameRu = "ProductNameRu22"
                        },
                        new
                        {
                            Id = 23,
                            ActiveSubstanceId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo23",
                            DescriptionEng = "DescriptionEng23",
                            DescriptionRu = "DescriptionRu23",
                            GroupId = 4,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo23",
                            ProductNameEng = "ProductNameEng23",
                            ProductNameRu = "ProductNameRu23"
                        },
                        new
                        {
                            Id = 24,
                            ActiveSubstanceId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo24",
                            DescriptionEng = "DescriptionEng24",
                            DescriptionRu = "DescriptionRu24",
                            GroupId = 5,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo24",
                            ProductNameEng = "ProductNameEng24",
                            ProductNameRu = "ProductNameRu24"
                        },
                        new
                        {
                            Id = 25,
                            ActiveSubstanceId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo25",
                            DescriptionEng = "DescriptionEng25",
                            DescriptionRu = "DescriptionRu25",
                            GroupId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo25",
                            ProductNameEng = "ProductNameEng25",
                            ProductNameRu = "ProductNameRu25"
                        },
                        new
                        {
                            Id = 26,
                            ActiveSubstanceId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo26",
                            DescriptionEng = "DescriptionEng26",
                            DescriptionRu = "DescriptionRu26",
                            GroupId = 2,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo26",
                            ProductNameEng = "ProductNameEng26",
                            ProductNameRu = "ProductNameRu26"
                        },
                        new
                        {
                            Id = 27,
                            ActiveSubstanceId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo27",
                            DescriptionEng = "DescriptionEng27",
                            DescriptionRu = "DescriptionRu27",
                            GroupId = 3,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo27",
                            ProductNameEng = "ProductNameEng27",
                            ProductNameRu = "ProductNameRu27"
                        },
                        new
                        {
                            Id = 28,
                            ActiveSubstanceId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo28",
                            DescriptionEng = "DescriptionEng28",
                            DescriptionRu = "DescriptionRu28",
                            GroupId = 4,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo28",
                            ProductNameEng = "ProductNameEng28",
                            ProductNameRu = "ProductNameRu28"
                        },
                        new
                        {
                            Id = 29,
                            ActiveSubstanceId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo29",
                            DescriptionEng = "DescriptionEng29",
                            DescriptionRu = "DescriptionRu29",
                            GroupId = 4,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo29",
                            ProductNameEng = "ProductNameEng29",
                            ProductNameRu = "ProductNameRu29"
                        },
                        new
                        {
                            Id = 30,
                            ActiveSubstanceId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DescriptionGeo30",
                            DescriptionEng = "DescriptionEng30",
                            DescriptionRu = "DescriptionRu30",
                            GroupId = 4,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "ProductNameGeo30",
                            ProductNameEng = "ProductNameEng30",
                            ProductNameRu = "ProductNameRu30"
                        });
                });

            modelBuilder.Entity("Data.Models.ProductPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPhotos");
                });

            modelBuilder.Entity("Data.Models.ArticlePhoto", b =>
                {
                    b.HasOne("Data.Models.Article", "Article")
                        .WithMany("ArticlePhotos")
                        .HasForeignKey("ArticleId");
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.HasOne("Data.Models.ActiveSubstance", "ActiveSubstance")
                        .WithMany("Products")
                        .HasForeignKey("ActiveSubstanceId");

                    b.HasOne("Data.Models.Group", "Group")
                        .WithMany("Products")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Data.Models.ProductPhoto", b =>
                {
                    b.HasOne("Data.Models.Product", "Product")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
